# basic options
title: tim-thompson
author: Tim Thompson
email: me@tim-thompson.co.uk
description: Personal dev blog, I definitely know what I'm doing...
twitter_username: timthompson141
github_username: tim-thompson

# Build settings
markdown: kramdown
url: http://tim-thompson.co.uk

plugins: [jekyll-paginate] 

paginate: 5
paginate_path: /page:num/

theme: jekyll-theme-minimal
