# basic options
title: Tim Thompson's Blog
author: Tim Thompson
email: me@tim-thompson.co.uk
description: My Blog for all things from productivity, code and work to photography, gamedev and knitting
twitter_username: timthompson141
github_username: tim-thompson

# Build settings
markdown: kramdown
theme: minima
