# basic options
title: tim-thompson
author: Tim Thompson
email: me@tim-thompson.co.uk
description: Personal dev blog, I definitely know what I'm doing...
twitter_username: timthompson141
github_username: tim-thompson
theme: jekyll-theme-minimal
permalink: /:title
url: http://tim-thompson.co.uk

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-feed

# Pagination Options
paginate: 5
paginate_path: /page:num/